### ISSUE TITLE
Readonly components require Deserialize

### ISSUE THREAD

**Issue by jjedelsky** [amethyst/amethyst-editor-sync#38]
https://github.com/randomPoison/amethyst-editor-sync/blob/6c0871e2e65e9cfbb5d54b395215c8871786363a/src/lib.rs#L327

Is there any reason why `read_components` needs `WriteComponentSet` and therefore `Deserialize`?

**Comment by randomPoison** [comment]
Nope! It's totally a mistake on my part 😓 Feel free to open a pull request fixing it if you'd like, otherwise I'll get this fixed in the next release 🙂

**Comment by randomPoison** [comment]
This was fixed in #40, it'll be released in version 0.4.
